/* ═══════════════════════════════════════════════════
   data.js — BRLO Business Data Layer
   ═══════════════════════════════════════════════════
   This file is the single source of truth for all
   registered business entries. To add a new business,
   copy a template block and fill in the fields.

   FIELDS REFERENCE:
     permitNo       — Official BRLO permit number
     businessName   — Registered business name
     catchphrase    — Tagline / slogan (optional)
     nature         — Type / nature of business
     section        — Class section (Archimedes | Aristotle | Galileo | Kepler)
     address        — Booth / establishment address
     owner          — Proprietor / business owner name
     members        — Array of { name, isLeader }
     email          — Business email address
     payment        — Accepted payment methods
     products       — Products or services offered
     logo           — Path to logo image, e.g. "logos/mylogo.png" (leave "" if none)
     dateRegistered — Date approved and registered
     socials        — Object with optional keys: facebook, instagram, tiktok, twitter, website
   ═══════════════════════════════════════════════════ */

const BUSINESSES = [

  {
    permitNo:       "BRLO-202604-50327",
    businessName:   "Happy Tummy",
    catchphrase:    "",
    nature:         "Online Food / Homemade Food Business",
    section:        "Kepler",
    address:        "Central Mindanao University Laboratory High School, Musuan, Maramag, Bukidnon",
    owner:          "Rhez Aleyah C. Capio",
    members: [
      { name: "Capio, Rhez Aleyah C.",            isLeader: false },
      { name: "Asok, Princess Bianca",             isLeader: false },
      { name: "Alba, Daniela Aurea G.",            isLeader: false },
      { name: "Castillo, Caesar Laurence F.",      isLeader: false },
      { name: "Dinglasa, Maria Leigh Lanie A.",    isLeader: false },
      { name: "Dumandan, Carl Gian",               isLeader: false },
    ],
    email:          "princessbiancaasok@gmail.com",
    payment:        "Cash, GCash",
    products:       "Food options: Mac n Cheese, Chicken Alfredo, and Lasagna",
    logo:           "logo/happy_tummy.jpg",
    dateRegistered: "April 7, 2026",
    socials: {
      facebook:  "",
      instagram: "https://www.instagram.com/happytummyyyy_?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==",
      tiktok:    "",
      twitter:   "",
      website:   "",
    },
   coverPhotos: [
      "cover/happytummy_1.jpg",
      "",
      "",
    ],
  },

  {
    permitNo:       "BRLO-202604-24908",
    businessName:   "Bite Me, Baby?",
    catchphrase:    "Lamian nga pagkaon, labaw na ang nagkaon",
    nature:         "Food Cart / Street Food Stall",
    section:        "Archimedes",
    address:        "Near 11-Einstein Classroom, Central Mindanao University Laboratory High School",
    owner:          "Jeffrey III M. Galan",
    members: [
      { name: "Galan, Jeffrey III M.",          isLeader: false },
      { name: "Dinopol, Nolyn Mary A.",         isLeader: false },
      { name: "Guerra, Andre Nathaniel Y.",      isLeader: false },
      { name: "Ilasin, Astrid G.",              isLeader: false },
      { name: "Natividad, Reign P.",            isLeader: false },
      { name: "Ponce, Myrrh Zyrah O.",          isLeader: false },
      { name: "Salupado, Joery Benedict L.",    isLeader: false },
      { name: "Salvador, Princess Mierl D.",    isLeader: false },
      { name: "Tubo, Marc Allen D.",            isLeader: false },
    ],
    email:          "bitemebaby751@gmail.com",
    payment:        "Cash, GCash",
    products:       "Savory:The Messy Hookup (Nachos), Put a Ring on It (Onion Rings) | Sweets: Sugar Daddy Rods (Churros), Creamy Finish (Xiao Long Bao), For E Play (Ube Ricecake Turon) | Beverages: Buko PanDAMN (Buko Pandan), Chill Pill (Iced Tea)",
    logo:           "logo/bite_me_baby.jpg",
    dateRegistered: "April 7, 2026",
    socials: {
      facebook:  "https://www.facebook.com/share/1G9gCkmAde/",
      instagram: "https://www.instagram.com/bitemebaby143?igsh=Y3k1aHJhMDA0eDYw",
      tiktok:    "",
      twitter:   "",
      website:   "",
    },
    coverPhotos: [
      "",
      "",
      "",
    ],
  },

  {
    permitNo:       "BRLO-202604-58369",
    businessName:   "Part B and Friends",
    catchphrase:    "Basta si Adrian, busog imong tiyan.",
    nature:         "Snack and Drink Stall",
    section:        "Kepler",
    address:        "CMULHS Friendship Area, In front of Galileo",
    owner:          "Velez, Mhel Hudson S.",
    members: [
      { name: "Velez, Mhel Hudson S.",          isLeader: false },
      { name: "Parian, Angelah Nichole A.",      isLeader: false },
      { name: "Bermillo, Adrian Christanne E.",  isLeader: false },
      { name: "Paragoso, Alex Vincent S.",       isLeader: false },
      { name: "Martinez, Prince Archrow E.",     isLeader: false },
      { name: "Malacora, Kierk Brier V.",        isLeader: false },
    ],
    email:          "partbandfriends@gmail.com",
    payment:        "Cash",
    products:       "Blue Lemonade, Fruit Soda (Strawberry, Blueberry, Green Apple), Egg Sandwich, Fries, Nachos",
    logo:           "logo/part_b_friends.jpg",
    dateRegistered: "April 8, 2026",
    socials: {
      facebook:  "https://www.facebook.com/profile.php?id=61577457191424",
      instagram: "",
      tiktok:    "",
      twitter:   "",
      website:   "",
    },
    coverPhotos: [
      "cover/partb_1.jpg",
      "cover/partb_2.jpg",
      "cover/partb_3.jpg",
    ],
  },

  {
    permitNo:       "BRLO-202604-40820",
    businessName:   "Cookinamida",
    catchphrase:    "Cutie Ka, Palit Na!",
    nature:         "Food Cart / Street Food Stall",
    section:        "Archimedes",
    address:        "Inside CMULHS campus, right by the classrooms of Galileo and Einstein",
    owner:          "Cookinamida",
    members: [
      { name: "Abao, Alea G.",                  isLeader: false },
      { name: "Ajero, Princess Jureen Q.",       isLeader: false },
      { name: "Delfin, Andie Eunice P.",         isLeader: false },
      { name: "Derayunan, Mary Angelique I.",    isLeader: false },
      { name: "Garcia, Jana Emmly N.",           isLeader: false },
      { name: "Melgar, Ashley L.",               isLeader: false },
      { name: "Pasquil, Wincy Rose C.",          isLeader: false },
      { name: "Taghap, Jolie Mari M.",           isLeader: false },
    ],
    email:          "cookinamida@gmail.com",
    payment:        "Cash, GCash",
    products:       "Gimbap, Mochi, Popping Soda, Mango Bites, Rice Cake, Fish Cake, Quesadilla, Overload Fries",
    logo:           "logo/cookinamida.jpeg",
    dateRegistered: "April 8, 2026",
    socials: {
      facebook:  "",
      instagram: "https://www.instagram.com/cookinamida?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==",
      tiktok:    "",
      twitter:   "",
      website:   "",
    },
    coverPhotos: [
      "cover/cookinamida_1.jpg",
      "cover/cookinamida_2.jpg",
      "cover/cookinamida_3.jpg",
    ],
  },

  {
    permitNo:       "BRLO-202604-12942",
    businessName:   "Khave",
    catchphrase:    "",
    nature:         "Bakery & Pastry Shop",
    section:        "Kepler",
    address:        "Central Mindanao University Laboratory High School",
    owner:          "Khriste Leona M. Jaca",
    members: [
      { name: "Jaca, Khriste Leona M.",   isLeader: false },
      { name: "Pagayon, Zariena Vexa",    isLeader: false },
      { name: "Balo, Sophia Reign",       isLeader: false },
      { name: "Samulde, Jhezan Leamyr",   isLeader: false },
    ],
    email:          "leonajaca@gmail.com",
    payment:        "Cash, GCash",
    products:       "Ice Cream, Pastries",
    logo:           "logo/khave.png",
    dateRegistered: "April 8, 2026",
    socials: {
      facebook:  "",
      instagram: "",
      tiktok:    "",
      twitter:   "",
      website:   "",
    },
    coverPhotos: [
      "",
      "",
      "",
    ],
  },

  {
    permitNo:       "BRLO-202604-26015",
    businessName:   "Sa Kuan",
    catchphrase:    "Basta sa Kuan, Lamian!",
    nature:         "Food Cart / Street Food Stall",
    section:        "Archimedes",
    address:        "Central Mindanao University Laboratory High School, near Grade 11 Einstein Classroom",
    owner:          "Clarence Xavier C. Deita",
    members: [
      { name: "Abriol, Sarah Gwyneth I.",       isLeader: false },
      { name: "Agub, Precious Denise Marie C.", isLeader: false },
      { name: "Bardon, Churchill T.",           isLeader: false },
      { name: "Cagubcub, Kharylle Jhatme O.",   isLeader: false },
      { name: "Cenas, Kristine Kylle C.",       isLeader: false },
      { name: "Corda, Mary Wamy I.",            isLeader: false },
      { name: "Deita, Clarence Xavier C.",      isLeader: false },
      { name: "Menchavez, Phrety Calix N.",     isLeader: false },
      { name: "Ocoy, Matt Harvie S.",           isLeader: false },
    ],
    email:          "sakuan.lamian@gmail.com",
    payment:        "Cash, GCash",
    products:       "Fries with Blue Lemonade, Ala Buldak, Cinnamon Bites with Ice Cream, Pancone, Barbetlog (Rice or Java Rice with Chicken or Pork Barbecue with Egg), Mango Graham Tapioca, Ginaggang (Grilled Banana)",
    logo:           "logo/sa_kuan.jpeg",
    dateRegistered: "April 8, 2026",
    socials: {
      facebook:  "https://www.facebook.com/share/1CYaYDX4mL/?mibextid=wwXIfr",
      instagram: "https://www.instagram.com/didto_sakuan/",
      tiktok:    "https://www.tiktok.com/@kaonsakuan?_r=1&_d=f1mb0lj0me031d&sec_uid=MS4wLjABAAAAeZLH43J4livB0JyzkFpe98AbIytbDQYxziCWzntwiZaWsX0Q3js2_ZhIKRfCnhhc&share_author_id=7278676751081194502&sharer_language=en&source=h5_t&u_code=ea33lbd6a3f911&item_author_type=1&utm_source=copy&tt_from=copy&enable_checksum=1&utm_medium=ios&share_link_id=88F114F0-E844-43B9-9FB7-B503CA52AD37&user_id=7278676751081194502&sec_user_id=MS4wLjABAAAAeZLH43J4livB0JyzkFpe98AbIytbDQYxziCWzntwiZaWsX0Q3js2_ZhIKRfCnhhc&social_share_type=4&ug_btm=b8727,b0&utm_campaign=client_share&share_app_id=1180",
      twitter:   "",
      website:   "",
    },
    coverPhotos: [
      "cover/sakuan_1.jpg",
      "cover/sakuan_2.jpg",
      "cover/sakuan_3.jpg",
    ],
  },

  {
    permitNo:       "BRLO-202604-02414",
    businessName:   "NamEat",
    catchphrase:    "Basta NamEat, Namit Gid!",
    nature:         "Food Cart / Street Food Stall",
    section:        "Archimedes",
    address:        "Central Mindanao University Laboratory High School, Musuan, Maramag, Bukidnon",
    owner:          "Maredel Gwyneth R. Pelayo",
    members: [
      { name: "Cordoba, Augustus Christian R.", isLeader: false },
      { name: "Gatpandan, Britt Charles C.",    isLeader: false },
      { name: "Onyot, Bernard Dahlgren A.",     isLeader: false },
      { name: "Ando, Angel Rose C.",            isLeader: false },
      { name: "Blancaver, Samantha Nicole P.",  isLeader: false },
      { name: "Domasig, Sophia Nicole G.",      isLeader: false },
      { name: "Patricio, Jo Marian Alexa A.",   isLeader: false },
      { name: "Pelayo, Maredel Gwyneth R.",     isLeader: false },
    ],
    email:          "nameatgid@gmail.com",
    payment:        "Cash, GCash",
    products:       "Rice Meals, Fries, Nachos, Quesadillas, Milo Dinosaur, Matcha, Blue Lemonade, Cookies",
    logo:           "logo/nameat.png",
    dateRegistered: "April 8, 2026",
    socials: {
      facebook:  "",
      instagram: "",
      tiktok:    "",
      twitter:   "",
      website:   "",
    },
    coverPhotos: [
      "cover/nameat_1.jpg",
      "",
      "",
    ],
  },

  {
    permitNo:       "BRLO-202604-74960",
    businessName:   "Exue",
    catchphrase:    "Where flavor meets art.",
    nature:         "Food Cart / Street Food Stall",
    section:        "Archimedes",
    address:        "Central Mindanao University Laboratory High School - Grounds",
    owner:          "Gwyneth D. Braga",
    members: [
      { name: "Braga, Gwyneth D.",          isLeader: false },
      { name: "Alvaran, Kyle Krixxie B.",   isLeader: false },
      { name: "Martinez, Diana Abigail B.", isLeader: false },
      { name: "Borres, Ariana Leah B.",     isLeader: false },
      { name: "Gaan, Denise Lian A.",       isLeader: false },
      { name: "Estioko, Piel A.",           isLeader: false },
      { name: "Latayan, Helen Nicole P.",   isLeader: false },
      { name: "Palisbo, Christian Ken B.",  isLeader: false },
    ],
    email:          "exue6767@gmail.com",
    payment:        "Cash, GCash",
    products:       "Bento Box Lunch, Sushi, Empanada (Ham and Cheese), Iced Tea, Fruit Soda (Blueberry, Green Apple), Ice Cold Water, Iced Candy, Coffee Jelly",
    logo:           "logo/exue.jpg",
    dateRegistered: "April 8, 2026",
    socials: {
      facebook:  "https://www.facebook.com/share/1QnDF2eYSy/",
      instagram: "https://www.instagram.com/exue_official?igsh=cjh4ems1MHBxMmtm",
      tiktok:    "",
      twitter:   "",
      website:   "",
    },
    coverPhotos: [
      "",
      "",
      "",
    ],
  },

  {
    permitNo:       "BRLO-202604-61671",
    businessName:   "PAL CHIKS",
    catchphrase:    "",
    nature:         "Handicrafts & Novelty Items / Snacks and Rice Meal",
    section:        "Kepler",
    address:        "CMULHS, Front of Galileo",
    owner:          "Josh Saniel",
    members: [
      { name: "Badilla, Christine Ann",   isLeader: false },
      { name: "Fabroa, Zharich Athena",   isLeader: false },
      { name: "Basa, Veronika",           isLeader: false },
      { name: "Traza, Kristine Mae",      isLeader: false },
      { name: "Saniel, Josh",             isLeader: false },
      { name: "Divinagracia, Faith",      isLeader: false },
    ],
    email:          "badillachristineann63@gmail.com",
    payment:        "Cash, GCash",
    products:       "Rice Bowls, Japanese-inspired Snacks, Sticky Milk",
    logo:           "logo/pal_chiks.jpeg",
    dateRegistered: "April 8, 2026",
    socials: {
      facebook:  "",
      instagram: "https://www.instagram.com/pal.chiks?igsh=MXBuZDRnZmZmeDlnMA==",
      tiktok:    "",
      twitter:   "",
      website:   "",
    },
    coverPhotos: [
      "",
      "",
      "",
    ],
  },

  {
    permitNo:       "BRLO-202604-31609",
    businessName:   "Din Tai Food",
    catchphrase:    "Once matilawan, Dili Kalimtan",
    nature:         "Food Cart / Street Food Stall",
    section:        "Galileo",
    address:        "Central Mindanao University Laboratory High School",
    owner:          "Troy Michael C. Elemios",
    members: [
      { name: "Balbutin, Dave Jariel P.",   isLeader: false },
      { name: "Damayo, Katheeline B.",      isLeader: false },
      { name: "Daliva, John Adrian A.",     isLeader: false },
      { name: "Delada, Luis Aidan R.",      isLeader: false },
      { name: "Elemios, Troy Michael C.",   isLeader: false },
      { name: "Omas-as, Ariel A. Jr.",      isLeader: false },
      { name: "Ritardo, Catherine L.",      isLeader: false },
      { name: "Kilat, Gabrielle Glenn A.",  isLeader: false },
    ],
    email:          "elemios.troymichael@gmail.com",
    payment:        "Cash, GCash",
    products:       "Omecanton, Mojo Fries, Spam Musubi, Japanese Sando, Coffee Jelly, Buko Juice",
    logo:           "logo/dtf.png",
    dateRegistered: "April 8, 2026",
    socials: {
      facebook:  "https://www.facebook.com/profile.php?id=61577116842401",
      instagram: "",
      tiktok:    "",
      twitter:   "",
      website:   "",
    },
    coverPhotos: [
      "",
      "",
      "",
    ],
  },

  {
    permitNo:       "BRLO-202604-71270",
    businessName:   "ChickCheven",
    catchphrase:    "Chick cheeeveeennnnn",
    nature:         "Food Cart / Street Food Stall",
    section:        "Aristotle",
    address:        "CMULHS Back Area",
    owner:          "Jeysah Mercado",
    members: [
      { name: "Aliado, Michell Jane",        isLeader: false },
      { name: "Melgar, Christar Jerich",     isLeader: false },
      { name: "Azuelo, Andrew Michael",      isLeader: false },
      { name: "Medina, Mary Gabrielle",      isLeader: false },
      { name: "Boquila, Gabriel Alejandro",  isLeader: false },
      { name: "Mercado, Jeysah",             isLeader: false },
      { name: "Camarillo, Mary Bless",       isLeader: false },
      { name: "Sevilleno, Kristine Claire",  isLeader: false },
      { name: "Chavez, Guilliana",           isLeader: false },
    ],
    email:          "s.mercado.jeysah@gmail.com",
    payment:        "Cash, GCash, GoTyme",
    products:       "Food: Snow Cheese, Cheddar Cheese, Honey Glaze, Yangnyeom. Drinks: Blue Lemonade. Desserts: Muffins, Munchkins",
    logo:           "logo/chick_cheven.png",
    dateRegistered: "April 8, 2026",
    socials: {
      facebook:  "",
      instagram: "https://www.instagram.com/chickcheven_?igsh=MmVzaHFwamg2a2dm",
      tiktok:    "",
      twitter:   "",
      website:   "",
    },
    coverPhotos: [
      "cover/67_1.jpg",
      "cover/67_2.jpg",
      "",
    ],
  },

  {
    permitNo:       "BRLO-202604-00150",
    businessName:   "Puds Ni Pads",
    catchphrase:    "Lami na gali ang niluto, lami pajud ang galuto!",
    nature:         "Food Cart / Street Food Stall",
    section:        "Aristotle",
    address:        "CMULHS (Back Area), Near Intersection of Canteen",
    owner:          "Elijakier L. Bahian",
    members: [
      { name: "Bahian, Elijakier L.",        isLeader: false },
      { name: "Bagonoc, Jethro Renz E.",     isLeader: false },
      { name: "Cagol, Jelo Louie Manuel S.", isLeader: false },
      { name: "Chan, Paul Crichton D.",      isLeader: false },
      { name: "Gayo, Vann Anthony L.",       isLeader: false },
      { name: "Kamna, Nier Chrisdale B.",    isLeader: false },
      { name: "Martinez, Orl Glenarth B.",   isLeader: false },
      { name: "Pelarmo, Edrianne John G.",   isLeader: false },
      { name: "Sariana, Benedict G.",        isLeader: false },
    ],
    email:          "manolassemble@gmail.com",
    payment:        "Cash, GCash",
    products:       "Tokneneng, Kwek-Kwek, Tempura, Squid Ball, Fishball, Chicken Biryani, Ice Candy, Buko Juice",
    logo:           "logo/puds_ni_pads.png",
    dateRegistered: "April 8, 2026",
    socials: {
      facebook:  "",
      instagram: "",
      tiktok:    "",
      twitter:   "",
      website:   "",
    },
    coverPhotos: [
      "cover/puds_1.jpg",
      "cover/puds_2.jpg",
      "",
    ],
  },

  {
    permitNo:       "BRLO-202604-50190",
    businessName:   "Chimu ♡ Bento",
    catchphrase:    "",
    nature:         "Food Cart / Street Food Stall",
    section:        "Aristotle",
    address:        "CMULHS, Back Side, Friendship Area",
    owner:          "Chimu ♡ Bento",
    members: [
      { name: "Manlapaz, Herbbie Christine T.",    isLeader: false },
      { name: "Balbutin, Klint Weannard D.",       isLeader: false },
      { name: "Balendres, Erienne Xedric R.",      isLeader: false },
      { name: "Maderse, Hailey Steffanie A.",      isLeader: false },
      { name: "Maniego, Shynne Bless S.",          isLeader: false },
      { name: "Merla, Naomi Sabina D.",            isLeader: false },
      { name: "Quirog, Blaine Daniel A.",          isLeader: false },
      { name: "Villahermosa, Samuel Benedict M.",  isLeader: false },
    ],
    email:          "chimubento@gmail.com",
    payment:        "Cash, GCash",
    products:       "Bento Meals: Pork Katsu, Chicken Katsu, Omurice (Sauce: Pink Sauce, Katsu Sauce, Ketchup) | Ice Cones | Potato Mochi | Live Drawing Portrait | Chibi/Anime Art Commissions (Traditional and Digital) | Art Prints (custom) | Pins (custom)",
    logo:           "logo/chimu_bento.png",
    dateRegistered: "April 8, 2026",
    socials: {
      facebook:  "https://www.facebook.com/profile.php?id=61588529277891",
      instagram: "",
      tiktok:    "",
      twitter:   "",
      website:   "",
    },
    coverPhotos: [
      "cover/chimu_1.jpg",
      "cover/chimu_2.jpg",
      "cover/chimu_3.jpg",
    ],
  },

  {
    permitNo:       "BRLO-202604-77489",
    businessName:   "Fruititos Corner™",
    catchphrase:    "Fuel your Day the Tito Way.",
    nature:         "Milk Tea / Juice / Beverage Bar",
    section:        "Archimedes",
    address:        "Along the Pathway to SHS Classrooms via Boys CR, Central Mindanao University Laboratory High School, Musuan, Maramag, Bukidnon",
    owner:          "Kier Nethaniel C. Alburo",
    members: [
      { name: "Alburo, Kier Nethaniel C.",         isLeader: false },
      { name: "Araneta, Jeremiah Francis",          isLeader: false },
      { name: "Bagaporo, Bob II T.",                isLeader: false },
      { name: "Bernal, Prinze John Crain R.",       isLeader: false },
      { name: "Delante, Daniel Rey M.",             isLeader: false },
      { name: "Gamutan, Czangee Clark Vincent L.",  isLeader: false },
      { name: "Maunte, Aljeb P.",                  isLeader: false },
      { name: "Llaguna, Kirth Laurence A.",         isLeader: false },
      { name: "Rapal, Clyde Janren B.",             isLeader: false },
    ],
    email:          "fruititoscorner@gmail.com",
    payment:        "Cash, GCash",
    products:       "Fruit Cups, Fruit Salad, Fruit Juice, Calamansinade, Mango Float",
    logo:           "logo/fruititos.jpg",
    dateRegistered: "April 8, 2026",
    socials: {
      facebook:  "https://www.facebook.com/share/1HNVMdipRn/",
      instagram: "https://www.instagram.com/fruitit0s?igsh=MWVocWg4aG03N2xpcg==",
      tiktok:    "",
      twitter:   "",
      website:   "",
    },
    coverPhotos: [
      "cover/fruititos_1.jpg",
      "cover/fruititos_2.jpg",
      "cover/fruititos_3.jpg",
    ],
  },

  {
    permitNo:       "BRLO-202604-76784",
    businessName:   "GWENPANADA AND FRIENDS",
    catchphrase:    "Gwenpanada ano tara?",
    nature:         "Food Cart / Street Food Stall",
    section:        "Aristotle",
    address:        "CMU Laboratory High School, Friendship Area",
    owner:          "Gwyneth M. Canoy",
    members: [
      { name: "Canoy, Gwyneth M.",          isLeader: false },
      { name: "Ang, Tryxzhia Gem G.",       isLeader: false },
      { name: "Cordova, Kish Abiel C.",     isLeader: false },
      { name: "Dondonayos, Faith Zyra P.",  isLeader: false },
      { name: "Jore, Antonette T.",         isLeader: false },
      { name: "Lecena, Dhara Yvaine D.",    isLeader: false },
      { name: "Ugay, Cherish Angela D.",    isLeader: false },
      { name: "Ywayan, Lorraine Lyka B.",   isLeader: false },
    ],
    email:          "s.canoy.gwyneth@gmail.com",
    payment:        "Cash, GCash",
    products:       "Illorkish Gwenpanada, Choconet, Dumpching, Xiang Dwich, Green Sodondon, Pink Sodhar",
    logo:           "logo/gwenpanada.jpg",
    dateRegistered: "April 8, 2026",
    socials: {
      facebook:  "https://www.facebook.com/profile.php?id=61577406097694",
      instagram: "https://www.instagram.com/gwenpanada/",
      tiktok:    "",
      twitter:   "",
      website:   "",
    },
    coverPhotos: [
      "cover/gwen_1.jpg",
      "cover/gwen_2.jpg",
      "cover/gwen_3.jpg",
    ],
  },

  {
    permitNo:       "BRLO-202604-71699",
    businessName:   "SOUFFELAIRE",
    catchphrase:    "Where Taste Meets Quality",
    nature:         "Bakery & Pastry Shop / Home-based Café / Stall",
    section:        "Galileo",
    address:        "Near CMULHS Canteen",
    owner:          "Ramezes N. Bael",
    members: [
      { name: "Bael, Ramezes N.",             isLeader: false },
      { name: "Abcede, Krystel Jane",         isLeader: false },
      { name: "Bince, Kathleen Jon Marieth",  isLeader: false },
      { name: "Cutaran, Loreen Carell",       isLeader: false },
      { name: "Doromal, Vera Dominique",      isLeader: false },
      { name: "Griño, Glendi Angela",         isLeader: false },
      { name: "Marticio, Richard Jhay",       isLeader: false },
      { name: "Pagobo, Aaron Rhymar",         isLeader: false },
      { name: "Vergara, Florence Gem",        isLeader: false },
    ],
    email:          "souffelaire.ph@gmail.com",
    payment:        "Cash, GCash",
    products:       "Rice Meals: Chicken Teriyaki, Chicken Ala King, Chicken Katsu, Beef Shawarma Rice | Fruit Sodas: Watermelon, Pineapple, Blueberry, Grape, Green Apple | Pastries: S'mores Cookies, Matcha Cookies, Red Velvet Cookies, Classic Chocolate-chip Cookies, Oreo Cream-filled Pancakes, Mango Graham Cream-filled Pancakes, Cake Slices",
    logo:           "logo/souffelaire.png",
    dateRegistered: "April 8, 2026",
    socials: {
      facebook:  "https://www.facebook.com/share/1ccXyPoksQ/",
      instagram: "https://www.instagram.com/souffelaire?igsh=bGViZ21tNTZkOXdn",
      tiktok:    "https://www.tiktok.com/@souffelaire0?_r=1&_t=ZS-95MprXnq5nJ",
      twitter:   "",
      website:   "",
    },
    coverPhotos: [
      "",
      "",
      "",
    ],
  },
  {
  permitNo:       "BRLO-202604-93108",
  businessName:   "Munchies",
  catchphrase:    "We provide the most refreshing drinks, and fresh, delicious Sisig Rice Bowls!",
  nature:         "Milk Tea / Juice / Beverage Bar / Soda Stall and Eatery",
  section:        "Kepler",
  address:        "South Side of Recreational Area, In front of TLE Rooms",
  owner:          "Matthew James Guillen",
  members: [
    { name: "Borbon, Beau",              isLeader: false },
    { name: "Galilea, Paula",            isLeader: false },
    { name: "Guess, Kevin Alexander R.", isLeader: false },
    { name: "Guillen, Matthew James",    isLeader: false },
    { name: "Sinamban, Ivan Carlo",      isLeader: false },
  ],
  email:          "matthewguillen8@gmail.com",
  payment:        "Cash, GCash",
  products:       "Fruit Soda — 3 flavors: Blueberry, Blue Lemonade, Green Apple",
  logo:           "logo/munchies.webp",
  dateRegistered: "April 9, 2026",
  socials: {
    facebook:  "",
    instagram: "",
    tiktok:    "",
    twitter:   "",
    website:   "",
  },
  coverPhotos: [
      "",
      "",
      "",
    ],
},

{
  permitNo:       "BRLO-202604-96905",
  businessName:   "Mike & Match",
  catchphrase:    "Mix It. Match It. Love It.",
  nature:         "Restaurant / Eatery / Canteen",
  section:        "Galileo",
  address:        "Located at the walkway turning left after the canteen, white big tent",
  owner:          "Alforque, Ian Patrick",
  members: [
    { name: "Abaquita, Khiera Clyde",       isLeader: false },
    { name: "Alforque, Ian Patrick",        isLeader: false },
    { name: "Cassion, Lee Benjamin",        isLeader: false },
    { name: "Caharian, Alessandra Grey",    isLeader: false },
    { name: "Cervantes, Shanine Althea",    isLeader: false },
    { name: "Lintawahan, Queenie",          isLeader: false },
    { name: "Pequiro, Noelle Trisha",       isLeader: false },
    { name: "Tabudlong, Theresa Fiona",     isLeader: false },
    { name: "Tan, Axlle Mike",              isLeader: false },
  ],
  email:          "pequiro.noelle@gmail.com",
  payment:        "Cash, GCash",
  products:       "Snacks: Waffles, Churros, Fried Oreos | Drinks: Fruit Soda, Lemonade | Rice Meals: Shrimp Tempura, Onigiri, Cordon Bleu Roll",
  logo:           "logo/mike_n_match.jpeg",
  dateRegistered: "April 9, 2026",
  socials: {
    facebook:  "https://www.facebook.com/share/1CjuCxZz5f/?mibextid=wwXIfr",
    instagram: "https://www.instagram.com/mike_and_match?igsh=aDlldTE5MDRyNm53",
    tiktok:    "",
    twitter:   "",
    website:   "",
  },
  coverPhotos: [
      "",
      "",
      "",
    ],
},

{
  permitNo:       "BRLO-202604-47597",
  businessName:   "Raize-Mael",
  catchphrase:    "",
  nature:         "Food Cart / Street Food Stall",
  section:        "Kepler",
  address:        "CMULHS, Friendship Area",
  owner:          "Raizelle Mae O. Paig",
  members: [
    { name: "Asok, Ily Seth Ysana",          isLeader: false },
    { name: "Paig, Raizelle Mae",            isLeader: false },
    { name: "Magtulis, Xavierha Trixy",      isLeader: false },
    { name: "Silao, Lourence Niño",          isLeader: false },
    { name: "Tambiga, Nathaniel",            isLeader: false },
  ],
  email:          "raizemael921@gmail.com",
  payment:        "Cash, GCash",
  products:       "Rice Bowls: Honey Garlic Chicken, Chao Fan, Corned Beef Pepper Lunch | Fruit Sodas",
  logo:           "logo/raize_mael.jpeg",
  dateRegistered: "April 9, 2026",
  socials: {
    facebook:  "",
    instagram: "",
    tiktok:    "",
    twitter:   "",
    website:   "",
  },
  coverPhotos: [
      "cover/raize_1.jpg",
      "",
      "",
    ],
},

{
  permitNo:       "BRLO-202604-21390",
  businessName:   "Picapicka",
  catchphrase:    "Take a pic while you take a pick!",
  nature:         "Photobooth / Homemade Food Business",
  section:        "Aristotle",
  address:        "Infront of TLE Room 1, CMU Laboratory High School",
  owner:          "Deanne Mitzi E. Casiñas",
  members: [
    { name: "Casiñas, Deanne Mitzi E.",     isLeader: false },
    { name: "Tunog, Kitt Szimone Althea F.", isLeader: false },
    { name: "Enoc, Aesha Keyzowie F.",      isLeader: false },
    { name: "Cajilog, Szhaire Rhaya U.",    isLeader: false },
    { name: "General, Sean John Jacob C.",  isLeader: false },
    { name: "Herrera, Niño Josef F.",       isLeader: false },
    { name: "Gerigdig, Antonia Victoria A.", isLeader: false },
    { name: "Quijal, Nieren Quine A.",      isLeader: false },
  ],
  email:          "seancalonia1030@gmail.com",
  payment:        "Cash, GCash",
  products:       "Spicy Noodle Soup, Lasagna Soup, Banana Pudding, Arancini Balls, Burntbust Cheesecake, Crepe Cakes, Egg Pops, Banana Cake, Cucumber Lemonade",
  logo:           "logo/pica_picka.jpeg",
  dateRegistered: "April 9, 2026",
  socials: {
    facebook:  "",
    instagram: "",
    tiktok:    "",
    twitter:   "",
    website:   "",
  },
  coverPhotos: [
      "cover/pica_1.jpg",
      "cover/pica_2.jpg",
      "cover/pica_3.jpg",
    ],
},

{
  permitNo:       "BRLO-202604-91110",
  businessName:   "Assorted Sigma",
  catchphrase:    "Sigma energy, assorted snacks. -Take the Leap.",
  nature:         "Food Cart / Street Food Stall",
  section:        "Aristotle",
  address:        "CMULHS Grounds",
  owner:          "Alyka Angela A. Abarquez",
  members: [
    { name: "Abarquez, Alyka Angela A.",    isLeader: false },
    { name: "Villareal, Stephanie Nicole",  isLeader: false },
    { name: "Villarta, Lennarth Kyle O.",   isLeader: false },
    { name: "Jeong, Mi Jin M.",             isLeader: false },
    { name: "Oracion, Phoebe Gail A.",      isLeader: false },
    { name: "Alburo, Mark Jude C.",         isLeader: false },
    { name: "Gallardo, Kristian R.",        isLeader: false },
  ],
  email:          "assortedsigma@gmail.com",
  payment:        "Cash",
  products:       "Savory Snacks: Loaded Chips, Gimbap, Shawarma/Java Rice. Desserts: Cookie Dip, S'mores Cookie, Magnum-inspired Ice Candy. Juices: Watermelon Refresher, Buko Juice. Arts & Crafts: Pins, Crocheted Items",
  logo:           "logo/assorted_sigma.jpg",
  dateRegistered: "April 13, 2026",
   socials: {
    facebook:  "https://www.facebook.com/profile.php?id=61574367689615",
    instagram: "https://www.instagram.com/assorted.sigma?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==",
    tiktok:    "",
    twitter:   "",
    website:   "",
  },
  coverPhotos: [
      "cover/sigma_1.jpg",
      "cover/sigma_2.jpg",
      "cover/sigma_3.jpg",
    ],
},

 {
  permitNo:       "BRLO-202604-78951",
  businessName:   "Hukariko",
  catchphrase:    "Good food, good mood",
  nature:         "Food Cart / Street Food Stall",
  section:        "Galileo",
  address:        "CMULHS, Friendship Area",
  owner:          "Hukariko",
  members: [
    { name: "Loreniana, Naethan Josh G.",  isLeader: false },
    { name: "Maniego, Shyrel Bless S.",    isLeader: false },
    { name: "Balasico, Coleene N.",        isLeader: false },
    { name: "Toledo, Xryza Sophia S.",     isLeader: false },
    { name: "Alabado, Allen Kyle L.",      isLeader: false },
    { name: "Carumba, Clint Alfon James I.", isLeader: false },
    { name: "Obguia, Kyrl Tristan B.",     isLeader: false },
    { name: "Aniñon, Joules B.",           isLeader: false },
  ],
  email:          "s.maniego.shyrelbless@gmail.com",
  payment:        "Cash, GCash",
  products:       "Chao Fan, Turron, Tornado Potato, Hotdogs, Fruit Shake, Iced Tea",
  logo:           "logo/hukariko.png",
  dateRegistered: "April 14, 2026",

  socials: {
    facebook:  "https://www.facebook.com/share/1Ghj7ff9AN/?mibextid=wwXIfr",
    instagram: "",
    tiktok:    "",
    twitter:   "",
    website:   "",
  },
  coverPhotos: [
      "",
      "",
      "",
    ],
},

{
    permitNo:       "BRLO-202604-63093",
    businessName:   "OnlyFrans",
    catchphrase:    "Grabe kalami dle maka dle",
    nature:         "Restaurant / Eatery / Canteen",
    section:        "Galileo",
    address:        "CMULHS",
    owner:          "Eugene Ivan Roy A. Relado",
    members: [
      { name: "Relado, Eugene Ivan Roy A.",   isLeader: false },
      { name: "Lamique, Janchris Louie P.",   isLeader: false },
      { name: "Limocon, Francis Ryan B.",     isLeader: false },
      { name: "Ortega, Xerxes Hamz C.",       isLeader: false },
      { name: "Paulin, Jarred B.",            isLeader: false },
      { name: "Salingay, Jose Andress O.",    isLeader: false },
      { name: "Urbiztondo, Sedruol D.",       isLeader: false },
      { name: "Yuson, Keith Frederick M.",    isLeader: false },
    ],
    email:          "janchrislamique5@gmail.com",
    payment:        "Cash, GCash",
    products:       "Kikiam, Kwek-Kwek, Tempura, Lemonade, Buko Juice, Frans Fries, Siomai",
    logo:           "logo/onlyfrans.jpg",
    dateRegistered: "April 15, 2026",

    socials: {
    facebook:  "",
    instagram: "https://www.instagram.com/onlyf_ransssss/",
    tiktok:    "",
    twitter:   "",
    website:   "",
  },
  coverPhotos: [
      "",
      "",
      "",
    ],
  },

  {
    permitNo:       "BRLO-202604-08331",
    businessName:   "Tilaw-Tilaw Ra",
    catchphrase:    "Take the risk to taste the best",
    nature:         "Food Cart / Street Food Stall/ Food Service & Retail",
    section:        "Galileo",
    address:        "Sayre Highway, University Town, Musuan, Maramag, Bukidnon, Philippines",
    owner:          "Natashya Althea S. Mañago",
    members: [
      { name: "Mañago, Natashya Althea S.",      isLeader: false },
      { name: "Alfarero, Glaiza O.",             isLeader: false },
      { name: "Balaba, Allyssandra Montyl D.",   isLeader: false },
      { name: "Caballero, Verrah Janes A.",      isLeader: false },
      { name: "Jumawan, Kyziah Thea Jezryl G.",  isLeader: false },
      { name: "Natinga, Samantha Nicole B.",     isLeader: false },
      { name: "Simpron, Emman Paolo M.",         isLeader: false },
      { name: "Zubiri, Zaira L.",               isLeader: false },
    ],
    email:          "theanatty@gmail.com",
    payment:        "Cash, GCash",
    products:       "Mushroom Pepper Steak, Buffalo Wings, Kimchi Fried Rice, Peach-Mango Pie, Chi-Chee",
    logo:           "logo/tilawtilaw.jpeg",
    dateRegistered: "April 17, 2026",

    socials: {
    facebook:  "",
    instagram: "https://www.instagram.com/tilaw2ra?igsh=MTFjNnVoNDVuMnV3OQ%3D%3D&utm_source=qr",
    tiktok:    "",
    twitter:   "",
    website:   "",
  },
  coverPhotos: [
      "",
      "",
      "",
    ],
  },

  // ── ADD NEW BUSINESSES BELOW ──────────────────────
  // {
  //   permitNo:       "BRLO-202604-XXXXX",
  //   businessName:   "Your Business Name",
  //   catchphrase:    "Your tagline here",
  //   nature:         "Nature of Business",
  //   section:        "Aristotle",
  //   address:        "Booth Location",
  //   owner:          "Owner Full Name",
  //   members: [
  //     { name: "Leader Name",  isLeader: true  },
  //     { name: "Member Name",  isLeader: false },
  //   ],
  //   email:          "email@example.com",
  //   payment:        "Cash, GCash",
  //   products:       "List your products / services here",
  //   logo:           "",
  //   dateRegistered: "April 11, 2026",
  //   socials: {
  //     facebook:  "",
  //     instagram: "",
  //     tiktok:    "",
  //     twitter:   "",
  //     website:   "",
  //   },
  // },
  // ── END OF TEMPLATE ───────────────────────────────

];